-- Tech Ali: orders table for GitHub Pages checkout
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null,
  city text not null,
  email text,
  address text not null,
  items jsonb not null,
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'))
);

alter table public.orders enable row level security;

-- Do not expose customer orders for reading/editing from the public website.
revoke all on table public.orders from anon, authenticated;

-- The storefront only needs to create new orders.
grant insert on table public.orders to anon, authenticated;

-- Visitors can create a new pending order, but cannot set another status.
drop policy if exists "Storefront can create pending orders" on public.orders;
create policy "Storefront can create pending orders"
on public.orders
for insert
to anon, authenticated
with check (
  status = 'pending'
  and total >= 0
  and jsonb_typeof(items) = 'array'
);
